# Generated by Django 5.1.1 on 2024-10-03 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PetTracker", "0004_alter_foster_orgphone_alter_organization_orgphone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="foster",
            old_name="orgPhone",
            new_name="fosterPhone",
        ),
    ]
