# Generated by Django 5.1.2 on 2024-10-11 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PetTracker', '0005_rename_orgphone_foster_fosterphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='petImage',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petRecords',
            field=models.FileField(blank=True, null=True, upload_to='media/'),
        ),
    ]
